# Generated by Django 6.1.1 on 2026-10-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='flanes/')),
                ('destacado', models.BooleanField(default=False)),
                ('descuento_inscrito', models.DecimalField(default=0, help_text='Porcentaje de descuento')),
            ],
            options={
                'verbose_name': 'Flan',
                'verbose_name_plural': 'Flanes',
                'ordering': ['nombre'],
            },
        ),
    ]
