# Generated by Django 6.1.1 on 2026-10-02 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='descuento_inscrito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento para clientes registrados (0 a 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
